name : docker-build
on: [push]
jobs: 
 install-flask:
  runs-on: ubuntu-latest
  
  steps:
   - name: checkout the code
     uses: actions/checkout@v4
   - name: install flask
     run: pip install flask

 build-image:
  runs-on: ubuntu-latest
  needs: install-flask 
  steps:
   - name: build progress
     uses: actions/checkout@v4
   - name: final build
     run: docker build -t flask_app   
